django_Tweet/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("tweet_app.urls")),
    path('', include('django.contrib.auth.urls'))
]

tweet_app/urls.py
from . import views
from django.urls import path

app_name ="tweet_app"

urlpatterns = [
    path('',views.ListTweet,name='listtweet'),
    path('addtweet/',views.AddTweet,name='addtweet'),
    path('signup/',views.SignUpView.as_view(), name="signup"),
    path('deletetweet/<int:id>',views.Tweet_delete,name="deletetweet")
]

tweet_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class tweet(models.Model):
    username = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    message = models.CharField(max_length=130)

    def __str__(self):
        return f"username: {self.username} message: {self.message} "

tweet_app/views.py
from django.shortcuts import render,redirect
from . import models
from django.urls import reverse,reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView 

# Create your views here.
def ListTweet(request):
    all_tweet = models.tweet.objects.all()
    context_tweet ={"tweets":all_tweet }
    return render(request,'tweet_app/ListTweet.html',context=context_tweet)

@login_required(login_url="/login")
def AddTweet(request):
    if request.POST:
       message =request.POST["message"]
       models.tweet.objects.create(username=request.user,message=message)
       return redirect(reverse('tweet_app:listtweet'))
    else:
        return render(request,'tweet_app/AddTweet.html')
    

@login_required
def Tweet_delete(request,id):
    tweet=models.tweet.objects.get(pk=id)
    if request.user == tweet.username:
        models.tweet.objects.filter(id=id).delete()
        return redirect('tweet_app:listtweet')

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

templates/base.html
<html lang="en">
  {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'tweet_app/ListTweet.css' %}">
    <style>
      body {
              min-height: 75rem;
              padding-top: 4.5rem;
              background-color: gray;
            }
            form{
              padding: 2rem;
            }
        .notifications-container {
        width: 320px;
        height: auto;
        font-size: 0.875rem;
        line-height: 1.25rem;
        display: flex;
        flex-direction: column;
        gap: 1rem;
        margin-bottom: 10px;
        margin-left: 35%;
      }

      .flex {
        display: flex;
      }

      .flex-shrink-0 {
        flex-shrink: 0;
      }

      .success {
        padding: 1rem;
        border-radius: 0.375rem;
        background-color: rgb(240 253 244);
      }

      .succes-svg {
        color: rgb(74 222 128);
        width: 1.25rem;
        height: 1.25rem;
      }

      .success-prompt-wrap {
        margin-left: 0.75rem;
      }

      .success-prompt-heading {
        font-weight: bold;
        color: rgb(22 101 52);
      }

      .success-prompt-prompt {
        margin-top: 0.5rem;
        color: rgb(21 128 61);
      }

      .success-button-container {
        display: flex;
        margin-top: 0.875rem;
        margin-bottom: -0.375rem;
        margin-left: -0.5rem;
        margin-right: -0.5rem;
      }

      .success-button-main {
        padding-top: 0.375rem;
        padding-bottom: 0.375rem;
        padding-left: 0.5rem;
        padding-right: 0.5rem;
        background-color: #ECFDF5;
        color: rgb(22 101 52);
        font-size: 0.875rem;
        line-height: 1.25rem;
        font-weight: bold;
        border-radius: 0.375rem;
        border: none;
      }

      .success-button-main:hover {
        background-color: #D1FAE5;
      }

      .success-button-secondary {
        padding-top: 0.375rem;
        padding-bottom: 0.375rem;
        padding-left: 0.5rem;
        padding-right: 0.5rem;
        margin-left: 0.75rem;
        background-color: #ECFDF5;
        color: #065F46;
        font-size: 0.875rem;
        line-height: 1.25rem;
        border-radius: 0.375rem;
        border: none;
      }
    </style>
    <title>TWEET APP</title>
    
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'tweet_app:listtweet'  %}">Tweet App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'tweet_app:listtweet'  %}">List Tweet</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tweet_app:addtweet'  %}">Add Tweet</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login'  %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout'  %}?next=/">Logout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tweet_app:signup'  %}?next=/">SignUp</a>
              </li>
            </ul>

          </div>
        </div>
      </nav>
      

    {% block content %}

    {% endblock %}

</body>
</html>

tweet_app/templates/tweet_app/AddTweet.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST" > 
    {% csrf_token %}
    
    <div class="mb-3" style="width: 50%;">
      <label for="message" class="form-label">message</label>
      <input type="text" class="form-control" id="message" name="message">
    </div>
    <button type="submit" class="btn btn-primary" style="background-color: #30344c;">Send Tweet</button>
  </form>
{% endblock%}

tweet_app/templates/tweet_app/ListTweet.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--
<ul>
    {% for tweet in tweets %}
     
    <h2>{{tweet.nickname}}</h2> 
    <h4>{{tweet.message}}</h4>
    {% endfor%}
</ul>
-->
{% for tweet in tweets %}
<div class="notifications-container">
  <div class="success">
    <div class="flex">
      <div class="flex-shrink-0">
        <svg class="succes-svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
        </svg>
      </div>
      <div class="success-prompt-wrap">
        <p class="success-prompt-heading">{{tweet.username}}</p>
        <div class="success-prompt-prompt">
          <p>{{tweet.message}}</p>
        </div>
        <div class="success-button-container">
          {% if tweet.username == user%}
          <button type="button" class="success-button-main">
            <a href="{%url 'tweet_app:deletetweet' id=tweet.id %}">Delete</a>
          </button>
          {% endif%}
        </div>
      </div>
    </div>
  </div>
</div>

  {% endfor%}


{% endblock%}